server.port : 8018

#localhost setup
spring:
  datasource:
    url: jdbc:postgres://localhost:5432/stonks
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto : create